name       : libndp
version    : 1.5
release    : 1
source     :
    - http://libndp.org/files/libndp-1.5.tar.gz : faf116ab70ce9514ec4e8573556025debea08f606e7f38b616de1f26e120c795
license    : LGPL-2.1
summary    : Neighbor Discovery library
description: |
    Neighbor Discovery library
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
