name       : libndp
version    : 1.6
release    : 3
source     :
    - http://libndp.org/files/libndp-1.6.tar.gz : 0c7dfa84e013bd5e569ef2c6292a6f72cfaf14f4ff77a77425e52edc33ffac0e
license    : LGPL-2.1
component  : network.base
summary    : Neighbor Discovery library
description: |
    Neighbor Discovery library
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
