name       : libndp
version    : 1.5
release    : 2
source     :
    - http://libndp.org/files/libndp-1.5.tar.gz : faf116ab70ce9514ec4e8573556025debea08f606e7f38b616de1f26e120c795
license    : LGPL-2.1
component  : network.base
summary    : Neighbor Discovery library
description: |
    Neighbor Discovery library
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
